### ISSUE TITLE
Live Search error messages

### ISSUE THREAD

**Issue by nisha-naeem** [nisha-naeem/WorkLog#4]
Live search error messages when a string is entered to the "comboBoxErrorData", preferably with a contains filter.

**Comment by ibrahimhuycn** [comment]
This issue was resolved on [commit](https://github.com/nisha-naeem/WorkLog/commit/249007e92672d10ee519ee50097492d86ceb3f5d) by using sync-fusion sfComboBox.
Good Work @nisha-naeem
